### ISSUE TITLE
Carry a created Student object across multiple pages

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#24]
Session variables can carry it, but that means I have to create a session variable that refers to the newly created Student object. Then create a new page variable on every page a student can visit and set that page variable to the Session variable that holds the instance of the created Student object.

**Comment by skiadas** [comment]
Aren't you loading some common file on every page? I thought your student object was created there? Don't session variables carry over from page to page?

**Comment by DaltonMcc** [comment]
I am creating the Student object on the navbar file from the SESSION variables, which is loaded onto all of the user pages. However, for files that don't have the navbar page I have to rely on creating new Session variables instead of "updating" the Student object. I do recreate the Student obj when I reenter the pages with the navbar file. Didn't know if there was an easier or better way of doing so.
