### ISSUE TITLE
Work on Class/OOP structure for Content libraries

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#25]
Main Content Class that holds all common variables between the 3 database tables: Audio, Video, and Etudes. 

This class should be using the query methods from the Database class to retrieve the Content's information. (_To avoid code duplication_)

**Comment by DaltonMcc** [comment]
@Skiadas would it be easier to create a single Class with the class methods being the queries to the database? For example, I have an `$ID `and `$table `properties that are used in the constructor. From there the methods would be something like:

```
function get_file_page() {
   $query = "SELECT page FROM $this->table WHERE id = $this->ID";
 
   $result = mysqli_fetch_array( mysqli_query($conn, $query) );
 
   return $result[0]; 
}
```

Using this type of methods VS creating extender classes with new properties, new methods, and inheritance. Whereas with creating an extension it would be:
```
class Etude extends Content {
    public $page;

   //parent::__constructor(...) { ... }

    function get_file_page() {
       return $this->page; 
    }
```

Thoughts?

**Comment by skiadas** [comment]
@DaltonMcc Yes I think one class makes more sense. You can also keep the connection as a property of the object so you don't have to pass it around. I would probably have:

- A method that actually does the database query, ensures the connection is there first, handles connection errors.
- "Wrapper" methods that call this method with specific queries, to achieve the separate kind of queries you need.
-  If you need requests that return a single value, than always returning arrays, you may need to add a layer between the two methods above, like methods called `findOne` and `findMany`.
