### ISSUE TITLE
Different Class Interaction

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#28]
I have created a Database Class that house SQL query "skeletons" such as:
```
function findOne($ID, $table, $column)
    {
      $query = "SELECT $column FROM $table WHERE id = $ID";
                                                                    //conn is a class property
      $result = mysqli_fetch_array( mysqli_query($this->conn, $query) );
 
      return $result[0];
    }
```

And I want to effectively **call** that method from a different class. I have a main functions file that _include_ the other classes. 
```
 //functions.php
 
 //Database class (dbconnect) and the necessary connection variables (parameters)
  require $_SERVER['DOCUMENT_ROOT'] . '/chops/hc07-chops/Database/dbconnect.php';
  require $_SERVER['DOCUMENT_ROOT'] . '/chops/hc07-chops/Database/parameters.php';

  //Classes
  include $_SERVER['DOCUMENT_ROOT'] . '/chops/hc07-chops/Functions/student_class.php';
  include $_SERVER['DOCUMENT_ROOT'] . '/chops/hc07-chops/Functions/content_class.php';
  
  //Database object that houses the Connection and query methods
  $Database = new Database($serverinfo);
```

I want to call the methods within the newly created Database object inside another class, such as:
```
class Content {

        public $ID;
        public $table;

	function get_file_address()
	{
		$Database->findOne($this->ID, $this->table, 'file');
	}
}
```

Not sure how to do this correctly. I'm thinking the Content Class **extends** off the Database Class?

**Comment by DaltonMcc** [comment]
It works correctly if the Content Class **EXTENDS** the Database Class; essentially calling the Database (aka the "parent" class) methods directly instead of statically.

```
Class Database {

//the connection to the database
private $conn;

function findOne($ID, $table, $column)
    {
      $query = "SELECT $column FROM $table WHERE id = $ID";
 
      $result = mysqli_fetch_array( mysqli_query($this->conn, $query) );

      Database::testForError($result);
 
      return $result[$column];
    }
}
```

```
Class Content extends Database {

//class properties

   //constructor used to initialize an object
   function __construct($ID, $table, $server)
   {
      //property assignments
      parent::__construct($server);
   }

   //Get the URL address of the file from the database
   function get_file_address()
   {
      return Database::findOne($this->ID, $this->table, 'file');
   }
}
```

My example is this:

```
$Database = new Database($server);

$content = new Content('1', 'chops_etudes', $server);

echo $content->get_file_address(); //displays the URL of the Etude with ID = 1
```

The only issue I have with this is I'm calling the Database constructor multiple times. Each new Content object is going to call the "parent" constructor and in this case it is the Database constructor that would create a new connection each time. The reason for this is how to use the the Database Class's one property, which is the connection. When calling a parent function from it's child class, the `$this` no longer points to the Database object, it points to the new Content object and the Content object does NOT have a `$conn` property. So executing a mysqli_query with `$this->conn` would have that variable be null; thus throwing an error.

Still working on this, but the solution of having the Content Class **extend** off the Database Class works. (And it works with Twig templates as well!)

**Comment by skiadas** [comment]
There is absolutely no logical reason why the content class should be extending the database class. 

I'm confused why the earlier thing you had wasn't working. You were creating a single instance, $Database (though I would probably hide its construction inside the Database class instead, have it return it following a Singleton pattern), were you unable to get it to work? What part precisely was failing? The earlier sample you had:

```
function get_file_address()
	{
		$Database->findOne($this->ID, $this->table, 'file');
	}
```
Should of course have a "return" there. Is that why it wasn't working?

I'm curious about the `Database::testForError($result);` call you are using, why is this a static method rather than an instance method?

**Comment by DaltonMcc** [comment]
I figured it was weird. This is what I have currently:

```
class Database {

    private $conn;
    private static $instance = null;

    private function __construct($server) 
    {
      $this->conn = mysqli_connect($server[0], $server[1], $server[2], $server[3]);

     //check for error
    }


    public static function connect($server)
    {
    	if (self::$instance == null)
    	{
    		self::$instance = new Database($server);
    	}

    	return self::$instance;
    }
```
and I call it using,
`$Database = Database::connect($serverinfo);`

```
Class Content {

   public $ID;
   public $table;

   function get_file_address()
   {
	return $Database->findOne($this->ID, $this->table, 'file');
   }
```
I create a new Content object: `$etude = new Content(...)`

and then I call the get_file_address method: `$etude->get_file_address()`

I get: `Notice: Undefined variable: Database in content_class.php`

Should I giving the get_file_address method the $Database variable directly?

------------------------------------------------------------------------------------------------------

Also, I fixed the testForError part. I changed it to:
`$this->testForError($resultgoeshere)`
