### ISSUE TITLE
Re: Improve Database Class further (Rudiment Banner)

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#33]
Need to add a few more query methods for the Rudiment Banner implementation. (Maybe have an extension somewhere? DB Class is getting pretty long)

- [x] Check student progress method. If the result is `Null` then it is "uncomplete." If there is a result and it returns `status == 1`, then it is "complete."
- [x] Update student progress query method
- [x] Remove entire student progress (on Student account deletion)

**Comment by DaltonMcc** [comment]
@skiadas My Database Class is getting long, about 300 lines, should I consider have an Extender Class for some more specific methods such as these on this issue? (Query methods for Student Progress -set/update/remove and Student Favorites -remove/add)

**Comment by skiadas** [comment]
You can if you want to, but I don't really see a need. It is still a reasonably small file, especially if you think of it in terms of lines of code.

If you were to split it up, I would not think of it in terms of extender classes. I would think of it in terms of layers. You have the lower layer that really manages the connection to the database, and another layer that makes various queries, and simply uses the lower layer. You can then create different files for the logically different kinds of queries, as you describe.
