### ISSUE TITLE
Favorite Button

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#34]
- [x] pushing button on unfavorited file calls Student method to add that file to Favorites and changes Bootstrap glyphicon.

**Comment by DaltonMcc** [comment]
Having a bit of trouble on this. I want this "event" to trigger two different things: 1) change the glyphicon in the button, and 2) call my PHP Student Class method of adding this file to the Favorites table. I have a separate file I'm testing out in and this is what I have:

```
<html>

<button id='favorite' class='btn btn-default btn-lg'>
<span class='glyphicon glyphicon-star-empty' aria-hidden='true'></span> Favorite! </button>

<script>
   //this gets the ID field of my button and when the button is pressed,
   //it calls a JS function written below.
   document.getElementById("favorite").onclick = function() {
         changeToFav()
   };

   function changeToFav() {
       //gets the button element associated with the ID tag = favorite
      //and reconstructs the same button but with a gold star glyphicon instead of an empty one
       document.getElementById("favorite").outerHTML = "<button class='btn btn-default btn-lg'><span class='glyphicon glyphicon-star' style='color:gold' aria-hidden='true'></span> Favorited! </button>";
      //sorry ^ that's ^ on one line, it complains if there is any spaces or if I use a JS str.concat method
		}
</script>
</html>
```

My initial button resembles this:
(empty glyphicon) Favorite!

and when I press it, it changes to:
(filled-on, Gold colored glyphicon) Favorited!

My question is, what JQuery/Ajax thing do I need to be able to "call" a PHP Class function in that same JS function `changeToFav()`?

I understand that JS and HTML are client-side and PHP is server-side so I need something (Ajax) to send something (https request?) to a PHP  file **with** arguments so that I may call a PHP Class method on the passed arguments. All while staying on the same page and the glyphicon button changes. 

@skiadas _Any suggestions?_ All the examples of using Ajax requests online are hard to understand.
(I realize it's late at night and I don't expect a response any time soon. I'll send you an email about it tomorrow sometime.)

**Comment by skiadas** [comment]
@DaltonMcc Basically ajax allows to you request a webpage, and receive the results, either json or html or xml, as an object, instead of changing the current page. So you'll basically be asking it for a full web address, probably ending in .php, and that can trigger whatever php work you want to put in it.

Are you using jQuery? Its ajax calls are a bit nicer I think.

What exactly do you need the php function to do? Just register that something was favorited? In that case it can be as simple as the function returning a 200 or 404/500, and you doing something based on that. Or you can look at specific content in the return. Probably returning some kind of JSON content would be the easiest result.

**Comment by DaltonMcc** [comment]
@skiadas I am not using JQuery at the moment. What I'm wanted it to do (php wise) is perform an insert query into the database. I already have a Class method for doing so. 

I could set up a small php file (maybe a couple lines) that have some sort of $_GET variable. It then calls my Class method using that $_GET variable as an argument. With Ajax, could I request that small php page and pass it the appropriate argument in the URL? Something like:
 '/chops/smallfile.php/content?=' 
and then concat the argument onto that so then the php file sees:
 '/chops/smallfile.php/content?=__someContentObject__

**Comment by skiadas** [comment]
Yeah you would do it though as '/chops/smallfile.php' and pass the arguments to the call via a separate way, at least if you use jQuery. I can't recall how the direct way does it, it would do it as '/chops/smallfile.php?key=value' if you do have to do it manually.

**Comment by DaltonMcc** [comment]
@skiadas I've seen the JQuery load() function: 
> $(selector).load(URL, data, callback);

> The required URL parameter specifies the URL you wish to load.

> The optional data parameter specifies a set of querystring key/value pairs to send along with the request.

At W3school's website; is that what you mean by "loading" a URL and passing the data in a different way?

**Comment by skiadas** [comment]
I think ajax is what you want, not load: http://api.jquery.com/jquery.ajax/
