### ISSUE TITLE
Slight Issue adding in the Resources Folder

### ISSUE THREAD

**Issue by DaltonMcc** [DaltonMcc/hc07-Chops#42]
This Folder has **_ALL_** the Content for the Database (all the audio tracks, video files, etudes, and pictures). Only problem is that it's almost **2GB** big. I have staged the file and attempted to push it to origin/master branch but it always times out and never lets me add it to the Repository.

**Comment by skiadas** [comment]
Try staging some files at a time, instead of the whole thing. Or doing it from the command line.
